name: Build and Push to Deploy Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Separate Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # or 'build'
          branch: gh-deploy

      - name: Deploy to Separate Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # or 'build'
          branch: gh-deploy

      - name: Trigger Hostinger Deployment
        run: |
          curl -i -X POST "${{ secrets.HOSTINGER_WEBHOOK_URL }}" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d ""